DuHoc/Models/Slide.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace DuHoc.Models
{
    public partial class Slide
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public int? Status { get; set; }
    }
}

DuHoc/ViewModels/Slide/SlideCreateRequest.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DuHoc.ViewModels.Slide
{
    public class SlideCreateRequest
    {

        [Required(ErrorMessage = "Bạn phải nhập tiêu đề")]
        [StringLength(500, ErrorMessage = "tiêu đề không quá 500 ký tự")]
        public string Title { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public int? Status { get; set; }


        [Required(ErrorMessage = "Chọn một file")]
        [Display(Name = "Chọn file upload")]
        public IFormFile FileUpload { get; set; }
    }
}

DuHoc/ViewModels/Slide/SlideUpdateRequest.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DuHoc.ViewModels.Slide
{
    public class SlideUpdateRequest
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập tiêu đề")]
        [StringLength(500, ErrorMessage = "tiêu đề không quá 500 ký tự")]
        public string Title { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public int? Status { get; set; }
        public IFormFile FileUpload { get; set; }
    }
}

DuHoc/ViewModels/Slide/SlideViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DuHoc.ViewModels.Slide
{
    public class SlideViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public int? Status { get; set; }
    }
}

DuHoc/Areas/Admin/Controllers/SlideController.cs
using DuHoc.Services;
using DuHoc.ViewModels.Slide;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace DuHoc.Areas.Admin.Controllers
{
    public class SlideController : BaseController
    {
        private readonly ISlideService _service;

        public SlideController(ISlideService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var lstSlide = await _service.GetAll();
            ViewBag.lstSlide = lstSlide;
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create(SlideCreateRequest request)
        {
            if (!ModelState.IsValid)
            {
                TempData["warning"] = "Bạn nhập thiếu dữ liệu";
                return View(request);
            }

            var result = await _service.Create(request);

            if (result != -1)
            {
                TempData["success"] = "Thêm mới Slide thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Thêm Slide thất bại");
            TempData["error"] = "Thêm mới Slide thất bại";
            return View(request);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var news = await _service.Edit(id);
            if (news == null)
            {
                TempData["warning"] = "Slide không tồn tại";
                return RedirectToAction("Index");
            }

            return View(news);
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Edit(SlideUpdateRequest request)
        {
            if (!ModelState.IsValid)
            {
                TempData["warning"] = "Bạn nhập thiếu dữ liệu";
                return View(request);
            }

            var result = await _service.Update(request);

            if (result == 1)
            {
                TempData["success"] = "Cập nhật Slide thành công";
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Cập nhật Slide thất bại");
                TempData["error"] = "Cập nhật Slide thất bại";
                return View(request);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var model = await _service.Detail(id);
            if (model == null)
            {
                TempData["warning"] = "Slide không tồn tại";
                return RedirectToAction("Index");
            }
            var result = await _service.Delete(id);
            if (result == 1)
            {
                TempData["success"] = "Xóa Slide thành công";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Xóa Slide thất bại";
            return RedirectToAction("Index");
        }
    }
}

DuHoc/Areas/Admin/Views/Slide/Create.cshtml
@model DuHoc.ViewModels.Slide.SlideCreateRequest
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@section css{
    <link href="~/admin/js/summernote/summernote-bs4.min.css" rel="stylesheet">
}

@section js{
    <script src="~/admin/js/summernote/summernote-bs4.js"></script>
    <script src="~/admin/js/custemUrl.js"></script>
    <script>
        $(document).ready(function () {
            $('#des').summernote({
                height: 200,
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'italic', 'underline', 'clear']],
                    ['fontname', ['fontname']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['height', ['height']],
                    ['table', ['table']],
                    ['insert', ['link', 'picture', 'hr']],
                    ['view', ['fullscreen', 'codeview']],
                    ['help', ['help']]
                ]
            });
        });
    </script>
}
<input type="hidden" id="success" value="@TempData["success"]" />
<input type="hidden" id="warning" value="@TempData["warning"]" />
<input type="hidden" id="error" value="@TempData["error"]" />

<div class="container-fluid">
    <h1 class="mt-4">Tạo mới Slide</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Tạo mới Slide</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Slide" asp-area="admin">Về danh sách</a>
        </div>

        <div class="card-body">
            <form asp-action="Create" asp-controller="Slide" asp-area="Admin" enctype="multipart/form-data" method="post">
                <div class="row">
                    <div class="col-md-8">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label class="control-label"> Tiêu đề Slide</label>
                            <input asp-for="Title" id="txtName" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label class="control-label">Mô tả</label>
                            <textarea asp-for="Description" id="des" rows="5" class="form-control"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Trạng thái</label>
                            <select class="form-control" id="Status" asp-for="Status">
                                <option value="1" selected>Hoạt động</option>
                                <option value="0">Khóa</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label class="control-label">Hình ảnh</label>
                            <input asp-for="FileUpload" type="file" class="form-control" />
                            <span asp-validation-for="FileUpload" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Tạo mới" class="btn btn-primary" />
                        </div>
                    </div>                 
            </form>
        </div>
    </div>
</div>

DuHoc/Areas/Admin/Views/Slide/Edit.cshtml
@model DuHoc.ViewModels.Slide.SlideUpdateRequest
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section css{
    <link href="~/admin/js/summernote/summernote-bs4.min.css" rel="stylesheet">
}

@section js{
    <script src="~/admin/js/summernote/summernote-bs4.js"></script>
    <script src="~/admin/js/custemUrl.js"></script>
    <script>
        $(document).ready(function () {
            $('#des').summernote({
                height: 200,
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'italic', 'underline', 'clear']],
                    ['fontname', ['fontname']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['height', ['height']],
                    ['table', ['table']],
                    ['insert', ['link', 'picture', 'hr']],
                    ['view', ['fullscreen', 'codeview']],
                    ['help', ['help']]
                ]
            });
        });
    </script>
}
<input type="hidden" id="success" value="@TempData["success"]" />
<input type="hidden" id="warning" value="@TempData["warning"]" />
<input type="hidden" id="error" value="@TempData["error"]" />

<div class="container-fluid">
    <h1 class="mt-4">Cập nhật Slide</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Cập nhật Slide</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="Slide" asp-area="admin">Về danh sách</a>
        </div>

        <div class="card-body">
            <form asp-action="Edit" asp-controller="Slide" asp-area="Admin" enctype="multipart/form-data" method="post">
                <div class="row">
                    <div class="col-md-8">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" value="@Model.Id" class="form-control" />
                        <div class="form-group">
                            <label class="control-label"> Tiêu đề Slide</label>
                            <input asp-for="Title" id="txtName" value="@Model.Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Mô tả</label>
                            <textarea asp-for="Description" id="des" value="@Model.Description" rows="5" class="form-control"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Trạng thái</label>
                            <select class="form-control" id="Status" asp-for="Status">
                                @if (Model.Status == 1)
                                {
                                    <option value="1" selected>Hoạt động</option>
                                    <option value="0">Khóa</option>
                                }
                                else
                                {
                                    <option value="1">Hoạt động</option>
                                    <option value="0" selected>Khóa</option>
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Hình ảnh</label>
                            <input asp-for="FileUpload" type="file" class="form-control" />
                            <span asp-validation-for="FileUpload" class="text-danger"></span>
                            <img src="@Model.Url" style="width: 150px;" />
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Cập nhật" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

DuHoc/Areas/Admin/Views/Slide/Index.cshtml
@model DuHoc.ViewModels.Slide.SlideViewModel
@{
    Layout = "_LayoutAdmin";
    var lstSlides = (List<DuHoc.ViewModels.Slide.SlideViewModel>)ViewBag.lstSlide;
}

<input type="hidden" id="success" value="@TempData["success"]" />
<input type="hidden" id="warning" value="@TempData["warning"]" />
<input type="hidden" id="error" value="@TempData["error"]" />

<div class="container-fluid">
    <h1 class="mt-4">Danh sách Slide</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Danh sách Slide</li>
    </ol>
    <div class="card mb-12">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <a class="btn btn-success" asp-action="Create" asp-controller="Slide" asp-area="admin">Tạo mới</a>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                @if (lstSlides.Count() > 0)
                {
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Hình ảnh</th>
                                <th>Tên</th>
                                <th>Mô tả</th>
                                <th>Trạng thái</th>
                                <th>#</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                var stt = 0;
                                @foreach (var item in lstSlides)
                                {
                            <tr>
                                <td>@Html.Raw(stt = stt + 1)</td>
                                <td><img src="@item.Url" style="width:80px;" /></td>
                                <td>@item.Title</td>
                                <td>@item.Description</td>
                                @if (item.Status == 1)
                                {
                                    <td><span class="btn-success">Hoạt động</span></td>
                                }
                                else
                                {
                                    <td><span class="btn-danger">Khóa</span></td>
                                }
                                <td>
                                    <a href="/Admin/Slide/Edit/@item.Id" class="btn btn-primary glyphicon glyphicon-pencilt"><i class="fa-solid fa-pencil"></i></a>
                                    <a class="btn btn-danger glyphicon glyphicon-trash" onclick="return confirm('Bạn có muốn xóa không?');" href="@Url.Action("Delete","Slide")/@item.Id"><i class="fa-solid fa-trash-can"></i></a>
                                </td>
                            </tr>
                                }
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <span>Không có Slide nào</span>
                }

            </div>
        </div>
    </div>
</div>