DuHoc/Models/Feedback.cs
using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace DuHoc.Models
{
    public partial class Feedback
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Status { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int? Phone { get; set; }
        public string Email { get; set; }
    }
}

DuHoc/ViewModels/FeedBack/FeedBackCreateRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DuHoc.ViewModels.FeedBack
{
    public class FeedBackCreateRequest
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập nội dung")]
        public string Message { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Status { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập tên")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập địa chỉ")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập số điện thoại")]
        public int? Phone { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập email")]
        public string Email { get; set; }
    }
}

DuHoc/ViewModels/FeedBack/FeedBackRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DuHoc.ViewModels.FeedBack
{
    public class FeedBackRequest
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập nội dung")]
        public string Message { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Status { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập tên")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập địa chỉ")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập số điện thoại")]
        public int? Phone { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập email")]
        public string Email { get; set; }
    }
}

DuHoc/ViewModels/FeedBack/FeedBackUpdateRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DuHoc.ViewModels.FeedBack
{
    public class FeedBackUpdateRequest
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Status { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int? Phone { get; set; }
        public string Email { get; set; }
        public string Reply { get; set; }
    }
}

DuHoc/Areas/Admin/Controllers/FeedBackController.cs
using DuHoc.Email;
using DuHoc.Models;
using DuHoc.Services;
using DuHoc.ViewModels.FeedBack;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mail;
using System.Threading.Tasks;

namespace DuHoc.Areas.Admin.Controllers
{
    public class FeedBackController : BaseController
    {
        private readonly IFeedbackService _service;
        private ISendMailService _sendMailservice;

        public FeedBackController(IFeedbackService service, ISendMailService sendMailservice)
        {
            _service = service;
            _sendMailservice = sendMailservice;
        }
        public async Task<IActionResult> Index()
        {
            var fbs =await  _service.GetAll();
            ViewBag.fbs = fbs;
            return View();
        }

        public async Task<IActionResult> Detail(int id)
        {
            var res =await _service.Detail(id);
            return View(res);
        }

        public async Task<IActionResult> Confirm(FeedBackUpdateRequest fb)
        {

            var result =await _service.Update(fb.Id);


            MailContent content = new MailContent
            {
                To = fb.Email,
                Subject = "Phản hồi từ VJ",
                Body = fb.Reply
            };

            await _sendMailservice.SendMail(content);

            if (result == 1)
            {
                TempData["success"] = "Xác nhận thành công";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Xác nhận thất bại";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var model = await _service.Detail(id);
            if (model == null)
            {
                TempData["warning"] = "Phản hồi không tồn tại";
                return RedirectToAction("Index");
            }
            var result = await _service.Delete(id);
            if (result == 1)
            {
                TempData["success"] = "Xóa thành công";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Xóa thất bại";
            return RedirectToAction("Index");
        }

    }
}

DuHoc/Areas/Admin/Views/FeedBack/Detail.cshtml
@model DuHoc.ViewModels.FeedBack.FeedBackUpdateRequest
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section css{
    <link href="~/admin/js/summernote/summernote-bs4.min.css" rel="stylesheet">
}

@section js{
    <script src="~/admin/js/summernote/summernote-bs4.js"></script>
    <script src="~/admin/js/custemUrl.js"></script>
    <script>
        $(document).ready(function () {
            $('#reply').summernote({
                height: 200,
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'italic', 'underline', 'clear']],
                    ['fontname', ['fontname']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['height', ['height']],
                    ['table', ['table']],
                    ['insert', ['link', 'picture', 'hr']],
                    ['view', ['fullscreen', 'codeview']],
                    ['help', ['help']]
                ]
            });
        });
    </script>
}
<input type="hidden" id="success" value="@TempData["success"]" />
<input type="hidden" id="warning" value="@TempData["warning"]" />
<input type="hidden" id="error" value="@TempData["error"]" />

<div class="container-fluid">
    <h1 class="mt-4">Cập nhật phản hồi</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Cập nhật phản hồi</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="FeedBack" asp-area="admin">Về danh sách</a>
        </div>

        <div class="card-body">
            <form asp-action="Confirm" asp-controller="FeedBack" asp-area="Admin" method="post">
                <div class="row">
                    <div class="col-md-8">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" value="@Model.Id" class="form-control" />
                        <div class="form-group">
                            <label class="control-label"> Tên</label>
                            <input readonly asp-for="Name" id="txtName" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label class="control-label"> Email</label>
                            <input readonly asp-for="Email" id="txtUrl" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label class="control-label">Số điện thoại</label>
                            <input readonly asp-for="Phone" id="txtName" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label class="control-label">Địa chỉ</label>
                            <input readonly asp-for="Address" id="txtUrl" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label class="control-label">Lời nhắn</label>
                            <textarea readonly asp-for="Message" rows="5" class="form-control"></textarea>
                        </div>

                        <div class="form-group">
                            <label class="control-label">Trả lời</label>
                            <textarea asp-for="Reply" id="reply" class="form-control"></textarea>
                            <span asp-validation-for="Reply" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Trạng thái</label>
                            <select disabled class="form-control" id="Status" asp-for="Status">
                                @if (Model.Status == 1)
                                {
                                    <option value="1" selected>Đã xác nhận</option>
                                    <option value="0">Chưa xác nhận</option>
                                }
                                else
                                {
                                    <option value="1">Đã xác nhận</option>
                                    <option value="0" selected>Chưa xác nhận</option>
                                }
                            </select>
                        </div>
                        @*@if (Model.Status == 0)
                        {
                            <div class="form-group">
                                <input type="submit" value="Trả lời" class="btn btn-primary" />
                            </div>
                        }*@

                        <div class="form-group">
                            <input type="submit" value="Trả lời" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

DuHoc/Areas/Admin/Views/FeedBack/Index.cshtml
@{
    Layout = "_LayoutAdmin";
    var fbs = (List<DuHoc.Models.Feedback>)ViewBag.fbs;
}

<input type="hidden" id="success" value="@TempData["success"]" />
<input type="hidden" id="warning" value="@TempData["warning"]" />
<input type="hidden" id="error" value="@TempData["error"]" />

<div class="container-fluid">
    <h1 class="mt-4">Danh sách phản hồi</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Danh sách phản hồi</li>
    </ol>
    <div class="card mb-12">
        <div class="card-body">
            <div class="table-responsive">
                @if (fbs.Count() > 0)
                {
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Tên</th>
                                <th>Email</th>
                                <th>Địa chỉ</th>
                                <th>Số điện thoại</th>
                                <th>Địa chỉ</th>
                                <th>#</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                var stt = 0;
                                @foreach (var item in fbs)
                                {
                            <tr>
                                <td>@Html.Raw(stt = stt + 1)</td>
                                <td>@item.Name</td>
                                <td>@item.Email</td>
                                <td>@item.Address</td>
                                <td>@item.Phone</td>
                                @if (item.Status == 1)
                                {
                                    <td><span class="btn-success">Đã xác nhận</span></td>
                                }
                                else
                                {
                                    <td><span class="btn-danger">Chưa xác nhận</span></td>
                                }
                                <td>
                                    <a href="/Admin/FeedBack/Detail/@item.Id" class="btn btn-primary glyphicon glyphicon-pencilt"><i class="fa-solid fa-pencil"></i></a>
                                    <a class="btn btn-danger glyphicon glyphicon-trash" onclick="return confirm('Bạn có muốn xóa không?');" href="@Url.Action("Delete","FeedBack")/@item.Id"><i class="fa-solid fa-trash-can"></i></a>
                                </td>
                            </tr>
                                }
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <span>Không có phản hồi nào</span>
                }

            </div>
        </div>
    </div>
</div>